-- Studio Steward — SQLite schema (Phase 2)
--
-- Two append-friendly tables:
--   events  — every studio event the Steward observed (chokidar, git poller,
--             terminal exit, rec lifecycle, etc.). Marked processed_at when
--             the reactor has run its rules against the event.
--   tasks   — work items the reactor enqueued for the worker pool. Each
--             task carries an intent UUID that becomes the studioWrite()
--             intent tag, so all writes from one task share a UUID and a
--             single git commit.
--
-- Both use TEXT timestamps (ISO-8601) for human readability and SQLite
-- BETWEEN/comparison support. ULIDs are 26-char Crockford base32 strings
-- generated by db/ulid.js — lexicographically sortable, no collisions
-- across processes.

CREATE TABLE IF NOT EXISTS events (
  id           TEXT PRIMARY KEY,
  ts           TEXT NOT NULL,
  project      TEXT NOT NULL,
  source       TEXT NOT NULL,        -- chokidar | git | terminal | rec-status | repo | tool-use
  kind         TEXT NOT NULL,        -- file-changed | commit | exit | status | ...
  payload      TEXT NOT NULL,        -- JSON-encoded payload
  processed_at TEXT,                  -- NULL until reactor processes it
  outcome      TEXT                   -- matched | no-match | error | skipped
);

CREATE INDEX IF NOT EXISTS events_project_ts ON events (project, ts);
CREATE INDEX IF NOT EXISTS events_unprocessed ON events (processed_at) WHERE processed_at IS NULL;

CREATE TABLE IF NOT EXISTS tasks (
  id           TEXT PRIMARY KEY,     -- ULID; == intent UUID for studioWrite
  rule_id      TEXT NOT NULL,        -- which reactor rule produced this task
  event_id     TEXT NOT NULL REFERENCES events(id),
  enqueued_at  TEXT NOT NULL,
  started_at   TEXT,                  -- NULL until a worker claims it
  completed_at TEXT,
  outcome      TEXT,                  -- success | error | timeout | skipped-low-confidence
  output       TEXT,                  -- truncated stdout (~32KB)
  error        TEXT,
  worker_pid   INTEGER                -- crash recovery: tasks with non-null started_at and null completed_at
);

CREATE INDEX IF NOT EXISTS tasks_unclaimed ON tasks (enqueued_at) WHERE started_at IS NULL;
CREATE INDEX IF NOT EXISTS tasks_in_flight ON tasks (started_at) WHERE started_at IS NOT NULL AND completed_at IS NULL;
CREATE INDEX IF NOT EXISTS tasks_completed ON tasks (completed_at DESC) WHERE completed_at IS NOT NULL;

-- Schema version for future migrations
CREATE TABLE IF NOT EXISTS schema_meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT OR IGNORE INTO schema_meta (key, value) VALUES ('version', '1');
INSERT OR IGNORE INTO schema_meta (key, value) VALUES ('created_at', datetime('now'));
